/**
 * @file personAndCharacter.ts
 * @description '인물 & 캐릭터' 카테고리에 대한 예제 케이스 데이터입니다.
 */
import type { Case } from '../../types';

export const personAndCharacterCases: Case[] = [
  {
    id: 1,
    title: '일러스트를 피규어로',
    category: '인물 & 캐릭터',
    author: '@ZHO_ZHO_ZHO',
    sourceUrl: 'https://x.com/ZHO_ZHO_ZHO/status/1958539464994959715',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case1/input0.jpg'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case1/output0.jpg',
    prompt: "turn this photo into a character figure. Behind it, place a box with the character's image printed on it, and a computer showing the Blender modeling process on its screen. In front of the box, add a round plastic base with the character figure standing on it. set the scene indoors if possible",
    prompt_ko: "이 사진을 캐릭터 피규어로 만들어주세요. 뒤에는 캐릭터 이미지가 인쇄된 상자를 놓고, 컴퓨터 화면에는 블렌더 모델링 과정이 보이게 해주세요. 상자 앞에는 둥근 플라스틱 베이스를 추가하고 그 위에 캐릭터 피규어를 세워주세요. 가능하다면 실내를 배경으로 설정해주세요."
  },
  {
    id: 5,
    title: '다른 시대의 내 모습',
    category: '인물 & 캐릭터',
    author: '@AmirMushich',
    sourceUrl: 'https://x.com/AmirMushich/status/1960810850224091439',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case5/input.jpg'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case5/output.jpg',
    prompt: "Change the characer's style to [1970]'s classical [male] style\n\nAdd [long curly] hair, \n[long mustache], \nchange the background to the iconic [californian summer landscape]\n\nDon't change the character's face",
    prompt_ko: "캐릭터의 스타일을 [1970]년대 클래식한 [남성] 스타일로 바꿔주세요. [길고 곱슬거리는] 머리카락과 [긴 콧수염]을 추가하고, 배경을 상징적인 [캘리포니아 여름 풍경]으로 변경해주세요. 캐릭터의 얼굴은 바꾸지 마세요."
  },
  {
    id: 8,
    title: '손그림으로 여러 캐릭터 포즈 제어하기',
    category: '인물 & 캐릭터',
    author: '@op7418',
    sourceUrl: 'https://x.com/op7418/status/1960536717242573181',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case8/input.jpg'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case8/output.jpg',
    prompt: 'Have these two characters fight using the pose from Figure 3. Add appropriate visual backgrounds and scene interactions,Generated image ratio is 16:9',
    prompt_ko: '이 두 캐릭터가 세 번째 그림의 포즈를 사용하여 싸우게 해주세요. 적절한 시각적 배경과 장면 상호작용을 추가하고, 생성되는 이미지 비율은 16:9로 해주세요.'
  },
  {
    id: 11,
    title: '애니메이션 캐릭터를 실제 코스플레이어로',
    category: '인물 & 캐릭터',
    author: '@ZHO_ZHO_ZHO',
    sourceUrl: 'https://x.com/ZHO_ZHO_ZHO/status/1960946893971706306',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case11/input.jpg'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case11/output.jpg',
    prompt: 'Generate a photo of a girl cosplaying this illustration, with the background set at Comiket',
    prompt_ko: '이 일러스트를 코스프레하는 소녀의 사진을 생성하고, 배경은 코미케로 설정해주세요.'
  },
  {
    id: 12,
    title: '캐릭터 디자인 시트 생성',
    category: '인물 & 캐릭터',
    author: '@ZHO_ZHO_ZHO',
    sourceUrl: 'https://x.com/ZHO_ZHO_ZHO/status/1960669234276753542',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case12/input.jpg'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case12/output.jpg',
    prompt: 'Generate character design for me (Character Design)\n\nProportion design (different height comparisons, head-to-body ratio, etc.)\n\nThree views (front, side, back)\n\nExpression design (Expression Sheet) → like the image you sent\n\nPose design (Pose Sheet) → various common poses\n\nCostume design (Costume Design)',
    prompt_ko: '캐릭터 디자인을 생성해주세요 (캐릭터 디자인)\n\n비율 디자인 (다양한 키 비교, 머리-몸 비율 등)\n\n3면도 (정면, 측면, 후면)\n\n표정 디자인 (표정 시트) → 보내주신 이미지처럼\n\n포즈 디자인 (포즈 시트) → 다양한 일반적인 포즈\n\n의상 디자인 (의상 디자인)'
  },
  {
    id: 15,
    title: '다양한 헤어스타일로 변경',
    category: '인물 & 캐릭터',
    author: '@balconychy',
    sourceUrl: 'https://x.com/balconychy/status/1960665038504779923',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case15/output.jpg',
    prompt: 'Generate avatars of this person with different hairstyles in a 3x3 grid format',
    prompt_ko: '이 사람의 다양한 헤어스타일 아바타를 3x3 그리드 형식으로 생성해주세요.'
  },
  {
    id: 22,
    title: '캐릭터 의상 변경',
    category: '인물 & 캐릭터',
    author: '@skirano',
    sourceUrl: 'https://x.com/skirano/status/1960343968320737397',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case22/input.jpg'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case22/output.jpg',
    prompt: "Replace the person's clothing in the input image with the target clothing shown in the reference image. Keep the person's pose, facial expression, background, and overall realism unchanged. Make the new outfit look natural, well-fitted, and consistent with lighting and shadows. Do not alter the person's identity or the environment — only change the clothes.",
    prompt_ko: "입력 이미지 속 인물의 의상을 참조 이미지에 있는 목표 의상으로 교체해주세요. 인물의 포즈, 표정, 배경, 전반적인 사실감은 그대로 유지해주세요. 새 의상이 자연스럽고 잘 맞으며 조명 및 그림자와 일관되게 보이도록 해주세요. 인물의 정체성이나 환경은 변경하지 말고 오직 옷만 바꿔주세요."
  },
  {
    id: 25,
    title: '캐릭터 포즈 수정',
    category: '인물 & 캐릭터',
    author: '@arrakis_ai',
    sourceUrl: 'https://x.com/arrakis_ai/status/1955901155726516652',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case25/input.jpg'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case25/output.jpg',
    prompt: 'Have the person in the picture look straight ahead',
    prompt_ko: '사진 속 인물이 정면을 바라보게 해주세요.'
  },
  {
    id: 34,
    title: '참조 이미지로 캐릭터 표정 제어',
    category: '인물 & 캐릭터',
    author: '@ZHO_ZHO_ZHO',
    sourceUrl: 'https://x.com/ZHO_ZHO_ZHO/status/1963156830458085674',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case34/case.jpg'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case34/case.jpg',
    prompt: 'Character reference from Image 1 / Change to the expression from Image 2',
    prompt_ko: '이미지 1의 캐릭터를 참고하여 / 이미지 2의 표정으로 바꿔주세요.'
  },
  {
    id: 36,
    title: '가상 메이크업 체험',
    category: '인물 & 캐릭터',
    author: '@ZHO_ZHO_ZHO',
    sourceUrl: 'https://x.com/ZHO_ZHO_ZHO/status/1962778069242126824',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case36/case.jpg'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case36/case.jpg',
    prompt: 'Apply the makeup from Image 2 to the character in Image 1, while maintaining the pose from Image 1.',
    prompt_ko: '이미지 1의 포즈는 유지하면서, 이미지 2의 메이크업을 이미지 1의 캐릭터에게 적용해주세요.'
  },
  {
    id: 40,
    title: '다양한 캐릭터 포즈 생성',
    category: '인물 & 캐릭터',
    author: '@tapehead_Lab',
    sourceUrl: 'https://x.com/tapehead_Lab/status/1960878455299694639',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case40/case.jpg'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case40/case.jpg',
    prompt: 'Please create a pose sheet for this illustration, making various poses!',
    prompt_ko: '이 일러스트를 위한 포즈 시트를 만들어 주세요, 다양한 포즈로요!'
  },
  {
    id: 43,
    title: '캐릭터 얼굴 형태 제어',
    category: '인물 & 캐릭터',
    author: '@ZHO_ZHO_ZHO',
    sourceUrl: 'https://x.com/ZHO_ZHO_ZHO/status/1961802767493939632',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case43/case.jpg'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case43/case.jpg',
    prompt: 'Design the character from Image 1 as a chibi version according to the face shape from Image 2',
    prompt_ko: '이미지 1의 캐릭터를 이미지 2의 얼굴 형태에 따라 꼬마 버전으로 디자인해주세요.'
  },
  {
    id: 45,
    title: '레고 미니피규어 만들기',
    category: '인물 & 캐릭터',
    author: '@ZHO_ZHO_ZHO',
    sourceUrl: 'https://x.com/ZHO_ZHO_ZHO/status/1961395526198595771',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case45/input.jpg'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case45/output.jpg',
    prompt: 'Transform the person in the photo into a LEGO minifigure packaging box style, presented in isometric perspective. Label the box with the title "ZHOGUE". Inside the box, display the LEGO minifigure based on the person in the photo, along with their essential items (such as makeup, bags, or other items) as LEGO accessories. Beside the box, also display the actual LEGO minifigure itself, unpackaged, rendered in a realistic and vivid style.',
    prompt_ko: '사진 속 인물을 레고 미니피규어 포장 상자 스타일로 변환하여 아이소메트릭 뷰로 보여주세요. 상자에는 "ZHOGUE"라는 제목을 붙여주세요. 상자 안에는 사진 속 인물을 기반으로 한 레고 미니피규어와 함께, 그들의 필수품(화장품, 가방 등)을 레고 액세서리로 전시해주세요. 상자 옆에는 포장되지 않은 실제 레고 미니피규어도 사실적이고 생생한 스타일로 렌더링하여 보여주세요.'
  },
  {
    id: 63,
    title: '증명사진 만들기',
    category: '인물 & 캐릭터',
    author: '@songguoxiansen',
    sourceUrl: 'https://x.com/songguoxiansen/status/1963602241610551609',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case63/input.jpg'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case63/output.jpg',
    prompt: 'Crop the head and create a 2-inch ID photo with:\n  1. Blue background\n  2. Professional business attire\n  3. Frontal face\n  4. Slight smile',
    prompt_ko: '머리를 잘라 2인치 증명사진을 만들어주세요:\n  1. 파란색 배경\n  2. 전문적인 비즈니스 복장\n  3. 정면 얼굴\n  4. 약간의 미소'
  },
  {
    id: 70,
    title: '거대 인물 비계',
    category: '인물 & 캐릭터',
    author: '@songguoxiansen',
    sourceUrl: 'https://x.com/songguoxiansen/status/1965960484684968234',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case70/input.png'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case70/output.png',
    prompt: 'A hyper-realistic 3D render of the person in the image standing and taking a selfie. \nThe giant figure is surrounded by massive scaffolding, with many tiny construction workers working on it. \nThe scene is set in a city square, surrounded by modern buildings, moving vehicles (cars, buses), pedestrians, \nand a bright clear blue sky. The overall details are rich, presenting a photo-realistic texture with cinematic lighting effects.',
    prompt_ko: '이미지 속 인물이 서서 셀카를 찍는 모습을 초현실적인 3D 렌더링으로 표현해주세요. 거대한 인물은 거대한 비계에 둘러싸여 있고, 많은 작은 건설 노동자들이 작업하고 있습니다. 장면은 도시 광장을 배경으로 현대적인 건물, 움직이는 차량(자동차, 버스), 보행자, 그리고 밝고 맑은 푸른 하늘로 설정됩니다. 전반적인 디테일이 풍부하며, 영화 같은 조명 효과와 함께 사실적인 질감을 보여줍니다.'
  },
  {
    id: 77,
    title: '커스텀 캐릭터 이모티콘 팩 생성',
    category: '인물 & 캐릭터',
    author: '@vista8',
    sourceUrl: 'https://x.com/vista8/status/1966164427243458977',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case77/input.png'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case77/output.png',
    prompt: 'Using the character from Image 2, generate [x] emoji stickers based on various poses from Image 1.',
    prompt_ko: '이미지 2의 캐릭터를 사용하여 이미지 1의 다양한 포즈를 기반으로 [x]개의 이모티콘 스티커를 생성해주세요.'
  },
  {
    id: 81,
    title: '해적 수배 전단지',
    category: '인물 & 캐릭터',
    author: '@AI_Kei75',
    sourceUrl: 'https://x.com/old_pgmrs_will/status/1966053092371444029',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case81/input.png'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case81/output.png',
    prompt: "Using the original image, recreate a pirate's wanted poster drawn on parchment.\nBrown monochrome, with the texture of aged parchment.\nRetain the style and character design of the original image down to the smallest detail, and paste it large at the top of the wanted poster.\nA close-up of the face. Have the character wear a pirate hat.\nWrite the bounty amount at the bottom of the poster. The bounty amount will be random, and a fictitious currency unit will be used.\nBelow the bounty amount, write the crime in small letters. Use a fictitious language. English or Chinese characters may not be used.",
    prompt_ko: "원본 이미지를 사용하여 양피지에 그린 해적의 수배 전단지를 재현해주세요.\n갈색 단색으로, 오래된 양피지 질감을 표현해주세요.\n원본 이미지의 스타일과 캐릭터 디자인을 아주 작은 디테일까지 유지하고, 수배 전단지 상단에 크게 붙여주세요.\n얼굴 클로즈업. 캐릭터가 해적 모자를 쓰게 해주세요.\n전단지 하단에 현상금을 적어주세요. 현상금 액수는 무작위이며, 가상의 화폐 단위를 사용합니다.\n현상금 아래에는 작은 글씨로 죄목을 적어주세요. 가상의 언어를 사용하며, 영어 또는 한자는 사용할 수 없습니다."
  },
  {
    id: 86,
    title: '다크 고딕 타로 카드',
    category: '인물 & 캐릭터',
    author: '@ImperfectEngel',
    sourceUrl: 'https://x.com/ImperfectEngel/status/1961833518163481001',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case86/output.png',
    prompt: 'Generate a dark gothic tarot card featuring me from this image. Include [“AI Artist - Shira”] and [coffee, white fluffy chubby cat with pink bow, laptop, phone, headphones] as symbols, with moody shadows, intricate gothic borders, and mystical dark fantasy vibes.',
    prompt_ko: '이 이미지를 사용하여 나를 주인공으로 한 어두운 고딕 타로 카드를 생성해주세요. 상징으로 ["AI 아티스트 - Shira"]와 [커피, 핑크 리본을 단 희고 통통한 고양이, 노트북, 휴대폰, 헤드폰]을 포함하고, 분위기 있는 그림자, 복잡한 고딕 테두리, 신비로운 다크 판타지 느낌을 더해주세요.'
  },
  {
    id: 90,
    title: '버튜버 되기',
    category: '인물 & 캐릭터',
    author: '@AI_Kei75',
    sourceUrl: 'https://x.com/AI_Kei75/status/1967490141578236329',
    inputImages: ['https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case90/input.png'],
    outputImage: 'https://raw.githubusercontent.com/PicoTrex/Awesome-Nano-Banana-images/main/images/case90/output.png',
    prompt: "Create a fictional Vtuber and their streaming screen using the original image.\nThe Vtuber's hairstyle and clothing will be faithfully reproduced from the original image.\nThe Vtuber image will be 2.5D-like, so it is not necessary to perfectly reproduce the style of the original image. A moderate sense of three-dimensionality is also necessary.\nThe Vtuber's facial expression and pose may be changed from the original image. Have the Vtuber hold a game controller.\nPlace only the Vtuber's upper body in the bottom right of the screen. Place the streaming screen of the game being played in the center of the screen. Place the chat screen on the left side of the screen.\nThe screen ratio is set to a larger size for the game screen, and the upper half of the Vtuber's body is displayed smaller.\nThe background of the original image is completely ignored, as well as the original image pose.\nAdd a fictional streaming platform and browser UI to the top and bottom of the screen.\nThe aspect ratio of the generated image is independent of that of the original image.",
    prompt_ko: "원본 이미지를 사용하여 가상의 버튜버(Vtuber)와 방송 화면을 만들어주세요.\n버튜버의 헤어스타일과 의상은 원본 이미지를 충실하게 재현합니다.\n버튜버 이미지는 2.5D 스타일이므로 원본 이미지 스타일을 완벽하게 재현할 필요는 없으며, 적당한 입체감이 필요합니다.\n버튜버의 표정과 포즈는 원본 이미지와 다르게 변경할 수 있습니다. 버튜버가 게임 컨트롤러를 들고 있게 해주세요.\n화면 오른쪽 하단에는 버튜버의 상반신만 배치하고, 화면 중앙에는 플레이 중인 게임의 방송 화면을, 왼쪽에는 채팅 화면을 배치합니다.\n화면 비율은 게임 화면을 더 크게 설정하고, 버튜버의 상반신은 더 작게 표시합니다.\n원본 이미지의 배경과 포즈는 완전히 무시합니다.\n화면 상단과 하단에 가상의 스트리밍 플랫폼과 브라우저 UI를 추가합니다.\n생성된 이미지의 가로세로 비율은 원본 이미지와 무관합니다."
  },
  {
    id: 95,
    title: '셀카로 버블헤드 인형 만들기',
    category: '인물 & 캐릭터',
    author: '@thisdudelikesAI',
    sourceUrl: 'https://x.com/thisdudelikesAI/status/1920433372243136730',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/95/selfie-to-bobblehead-generator.png',
    prompt: 'Turn this photo into a bobblehead: enlarge the head slightly, keep the face accurate and cartoonify the body. [Place it on a bookshelf].',
    prompt_ko: '이 사진을 버블헤드 인형으로 바꿔주세요: 머리를 약간 키우고, 얼굴은 정확하게 유지하면서 몸은 만화처럼 만들어주세요. [책장에 놓아주세요].'
  },
  {
    id: 96,
    title: '커스텀 애니메이션 피규어',
    category: '인물 & 캐릭터',
    author: '@dotey',
    sourceUrl: 'https://x.com/dotey/status/1920851135516082246',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/96/custom-anime-figure-from-photo.png',
    prompt: 'Generate an anime-style figure photo placed on a desktop, presented from a casual, everyday snapshot perspective as if taken with a mobile phone. The figure model is based on the attached character photo, accurately reproducing the full body posture, facial expression, and clothing style of the person in the photo, ensuring the entire figure is fully rendered. The overall design is exquisite and detailed, with hair and clothing featuring natural, soft gradient colors and fine textures. The style leans towards Japanese anime, rich in detail, with realistic textures and a beautiful appearance.',
    prompt_ko: '책상 위에 놓인 애니메이션 스타일의 피규어 사진을 휴대폰으로 찍은 듯한 일상적인 스냅샷 관점에서 생성해주세요. 피규어 모델은 첨부된 인물 사진을 기반으로 하며, 사진 속 인물의 전신 자세, 표정, 의상 스타일을 정확하게 재현하여 전체 피규어가 완전히 렌더링되도록 합니다. 전체적인 디자인은 정교하고 섬세하며, 머리카락과 의상은 자연스럽고 부드러운 그라데이션 색상과 미세한 질감을 특징으로 합니다. 스타일은 일본 애니메이션에 가까우며, 디테일이 풍부하고 사실적인 질감과 아름다운 외관을 가집니다.'
  },
  {
    id: 97,
    title: '귀엽고 아늑한 뜨개질 인형',
    category: '인물 & 캐릭터',
    author: '@ZHO_ZHO_ZHO',
    sourceUrl: 'https://x.com/ZHO_ZHO_ZHO/status/1921148024861938077',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/97/cute_cozy_knitted_doll.png',
    prompt: 'A close-up, professionally composed photograph showcasing a hand-crocheted yarn doll gently cradled by two hands. The doll has a rounded shape, featuring the cute chibi image of the [upload image] character, with vivid contrasting colors and rich details. The hands holding the doll are natural and gentle, with clearly visible finger postures, and natural skin texture and light/shadow transitions, conveying a warm and realistic touch. The background is slightly blurred, depicting an indoor environment with a warm wooden tabletop and natural light streaming in from a window, creating a comfortable and intimate atmosphere. The overall image conveys a sense of exquisite craftsmanship and cherished warmth.',
    prompt_ko: '두 손으로 부드럽게 감싸 안은 손뜨개 실 인형을 보여주는 클로즈업 전문 사진. 인형은 둥근 모양이며, [업로드 이미지] 캐릭터의 귀여운 꼬마 이미지를 특징으로 하고, 생생한 대조 색상과 풍부한 디테일을 가지고 있습니다. 인형을 든 손은 자연스럽고 부드러우며, 손가락 자세가 선명하게 보이고, 자연스러운 피부 질감과 빛/그림자 전환이 따뜻하고 사실적인 느낌을 전달합니다. 배경은 약간 흐릿하며, 따뜻한 나무 탁자와 창문에서 들어오는 자연광이 있는 실내 환경을 묘사하여 편안하고 친밀한 분위기를 연출합니다. 전체 이미지는 정교한 장인 정신과 소중한 따뜻함을 전달합니다.'
  },
  {
    id: 112,
    title: '3D 꼬마 캐릭터 제안 장면',
    category: '인물 & 캐릭터',
    author: '@balconychy',
    sourceUrl: 'https://x.com/balconychy/status/1909417750587486469',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/1/example_proposal_scene_q_realistic.png',
    prompt: "Transform the two people in the photo into chibi-style 3D cartoon characters. Change the scene to a proposal setting, with a soft pastel-colored floral arch in the background. Use romantic tones for the overall background. Rose petals are scattered on the ground. While the characters are rendered in cute chibi 3D style, the environment—including the arch, lighting, and textures—should be realistic and photorealistic.",
    prompt_ko: "사진 속 두 사람을 꼬마 스타일의 3D 만화 캐릭터로 변환해주세요. 배경은 부드러운 파스텔 톤의 꽃 아치가 있는 프로포즈 장면으로 바꿔주세요. 전체 배경에 로맨틱한 톤을 사용하고, 땅에는 장미 꽃잎이 흩어져 있게 해주세요. 캐릭터는 귀여운 꼬마 3D 스타일로 렌더링하되, 아치, 조명, 질감 등 환경은 사실적이고 실사처럼 표현해주세요."
  },
  {
    id: 115,
    title: '3D 꼬마 중국 결혼식 장면',
    category: '인물 & 캐릭터',
    author: '@balconychy',
    sourceUrl: 'https://x.com/balconychy/status/1909418699150237917',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/4/example_q_chinese_wedding.png',
    prompt: "Transform the two people in the photo into chibi-style 3D cartoon characters, dressed in traditional Chinese wedding attire. The overall theme is a festive red Chinese-style wedding. The background features a decorative “囍” (double happiness) paper-cut pattern in a classic folk style. \nClothing (realistic texture, traditional details):\nMale: Wearing a red changpao and magua (traditional robe and jacket) embroidered with golden dragon motifs, symbolizing nobility and grandeur. A large red flower is tied on his chest, representing celebration and good fortune.\nFemale: Dressed in a red xiuhe wedding gown adorned with exquisite golden floral and phoenix embroidery, showcasing elegance and luxury. She wears delicate floral hair ornaments to enhance her gentle and graceful appearance.\nHeadwear:\nMale: A traditional red zhuangyuan (scholar) hat with golden patterns and a refined golden ornament at the top, exuding classic scholarly dignity.\nFemale: A phoenix crown adorned with a central red flower, gold 3D decorative elements, and hanging tassels—luxurious and full of classical charm.\nThis image should reflect the joy and blessing of a traditional Chinese wedding, with realistic textures for costumes and accessories, combined with stylized 3D chibi characters.",
    prompt_ko: "사진 속 두 사람을 전통 중국 결혼 예복을 입은 꼬마 스타일의 3D 만화 캐릭터로 변환해주세요. 전체적인 테마는 축제 분위기의 붉은 중국식 결혼식입니다. 배경에는 고전적인 민속 스타일의 '囍'(쌍희) 종이 오리기 장식이 있습니다.\n의상 (사실적인 질감, 전통적인 디테일):\n남성: 금색 용 무늬가 수놓아진 붉은 창파오와 마과(전통 예복)를 입고 있으며, 이는 고귀함과 웅장함을 상징합니다. 가슴에는 축하와 행운을 상징하는 큰 붉은 꽃이 달려 있습니다.\n여성: 정교한 금색 꽃과 봉황 자수가 장식된 붉은 슈허(绣禾) 웨딩드레스를 입고 있으며, 우아함과 고급스러움을 보여줍니다. 섬세한 꽃 머리 장식을 착용하여 부드럽고 우아한 모습을 강조합니다.\n머리 장식:\n남성: 금색 패턴과 상단의 세련된 금색 장식이 있는 전통적인 붉은 장원(장원) 모자를 쓰고 있으며, 고전적인 학자의 위엄을 풍깁니다.\n여성: 중앙에 붉은 꽃, 금색 3D 장식 요소, 그리고 늘어뜨린 술이 달린 봉황관을 쓰고 있으며, 화려하고 고전적인 매력이 가득합니다.\n이 이미지는 의상과 액세서리의 사실적인 질감과 스타일화된 3D 꼬마 캐릭터를 결합하여 전통 중국 결혼식의 기쁨과 축복을 반영해야 합니다."
  },
  {
    id: 122,
    title: '포털을 통과하는 캐릭터',
    category: '인물 & 캐릭터',
    author: '@dotey',
    sourceUrl: 'https://x.com/dotey/status/1908910838636765204',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/6/example_portal_crossing_handhold.png',
    prompt: "A 3D chibi-style version of the person in the photo is stepping through a glowing portal, reaching out and holding the viewer’s hand. As the character pulls the viewer forward, they turn back with a dynamic glance, inviting the viewer into their world.\nBehind the portal is the viewer’s real-life environment: a typical programmer’s study with a desk, monitor, and laptop, rendered in realistic detail. Inside the portal lies the character’s 3D chibi world, inspired by the photo, with a cool blue color scheme that sharply contrasts with the real-world surroundings.\nThe portal itself is a perfectly elliptical frame glowing with mysterious blue and purple light, positioned at the center of the image as a gateway between the two worlds.\nThe scene is captured from a third-person perspective, clearly showing the viewer’s hand being pulled into the character’s world. Use a 2:3 aspect ratio.",
    prompt_ko: "사진 속 인물의 3D 꼬마 스타일 버전이 빛나는 포털을 통과하며 시청자의 손을 내밀어 잡고 있습니다. 캐릭터가 시청자를 앞으로 당기면서, 역동적인 시선으로 뒤를 돌아보며 시청자를 자신의 세계로 초대합니다.\n포털 뒤에는 시청자의 실제 환경이 있습니다: 책상, 모니터, 노트북이 있는 전형적인 프로그래머의 서재가 사실적인 디테일로 렌더링됩니다. 포털 안에는 사진에서 영감을 받은 캐릭터의 3D 꼬마 세계가 펼쳐져 있으며, 실제 세계 환경과 뚜렷하게 대조되는 시원한 파란색 색조를 띕니다.\n포털 자체는 신비로운 파란색과 보라색 빛으로 빛나는 완벽한 타원형 프레임으로, 두 세계 사이의 관문으로 이미지 중앙에 위치합니다.\n장면은 3인칭 시점으로 포착되어, 시청자의 손이 캐릭터의 세계로 끌려 들어가는 모습을 명확하게 보여줍니다. 2:3 가로세로 비율을 사용하세요."
  },
  {
    id: 124,
    title: '사진을 3D Q-버전 스타일로',
    category: '인물 & 캐릭터',
    author: '@dotey',
    sourceUrl: 'https://x.com/dotey/status/1908194518345678865',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/13/example_photo_to_3d_q.png',
    prompt: "Transform the characters in the scene into 3D chibi-style figures, while keeping the original scene layout and their clothing exactly the same.",
    prompt_ko: "장면 속 캐릭터들을 3D 꼬마 스타일 피규어로 변환하되, 원래의 장면 배치와 의상은 그대로 유지해주세요."
  },
  {
    id: 129,
    title: '액션 피규어와 실제 인물이 한 프레임에',
    category: '인물 & 캐릭터',
    author: '@dotey',
    sourceUrl: 'https://x.com/dotey/status/1920994118580183316',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/20/action_figure_and_real_person_in_frame.png',
    prompt: "In a casual, everyday style as if shot on a mobile phone, an anime figure of [Jackie Chan] is placed on a desk, striking an exaggerated and cool pose, fully equipped. Simultaneously, the corresponding real-life person also appears in the frame, striking a similar pose to the figure, creating an interesting visual contrast with the figure and the real person in the same frame. The overall composition is harmonious and natural, delivering a warm and vibrant, true-to-life visual experience.",
    prompt_ko: "휴대폰으로 촬영한 듯한 평범하고 일상적인 스타일로, [성룡]의 애니메이션 피규어가 책상 위에 놓여 과장되고 멋진 포즈를 취하고 있으며, 모든 장비를 갖추고 있습니다. 동시에, 해당 실존 인물도 프레임에 등장하여 피규어와 비슷한 포즈를 취하며, 피규어와 실존 인물이 한 프레임에 담겨 흥미로운 시각적 대비를 이룹니다. 전체적인 구도는 조화롭고 자연스러우며, 따뜻하고 활기찬, 현실감 있는 시각적 경험을 선사합니다."
  },
  {
    id: 130,
    title: '꼬마 캐릭터 스티커 팩',
    category: '인물 & 캐릭터',
    author: '@leon_yuan2001',
    sourceUrl: 'https://x.com/leon_yuan2001/status/1923712069209293014',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/21/chibi_character_sticker_pack.png',
    prompt: `Please create a set of 9 Chibi stickers featuring [the character in the reference image], arranged in a 3x3 grid.\nDesign requirements:\n- Transparent background.\n- 1:1 square aspect ratio.\n- Consistent Chibi Ghibli cartoon style with vibrant colors.\n- Each sticker must have a unique action, expression, and theme, reflecting diverse emotions like "sassy, mischievous, cute, frantic" (e.g., rolling eyes, laughing hysterically on the floor, soul leaving body, petrified, throwing money, foodie mode, social anxiety attack). Incorporate elements related to office workers and internet memes.\n- Each character depiction must be complete, with no missing parts.\n- Each sticker must have a uniform white outline, giving it a sticker-like appearance.\n- No extraneous or detached elements in the image.\n- Strictly no text, or ensure any text is 100% accurate (no text preferred).`,
    prompt_ko: "[참고 이미지 속 캐릭터]를 주인공으로 한 9개의 꼬마 스티커 세트를 3x3 격자로 만들어 주세요.\n디자인 요구사항:\n- 투명 배경.\n- 1:1 정사각형 비율.\n- 일관된 꼬마 지브리 만화 스타일과 선명한 색상.\n- 각 스티커는 '새침한, 장난기 있는, 귀여운, 정신없는' 등 다양한 감정을 반영하는 독특한 행동, 표정, 테마를 가져야 합니다(예: 눈알 굴리기, 바닥에서 데굴데굴 구르며 웃기, 영혼 가출, 석화, 돈 뿌리기, 먹방 모드, 사회 불안 발작). 직장인 및 인터넷 밈과 관련된 요소를 포함하세요.\n- 각 캐릭터 묘사는 완전해야 하며, 빠진 부분이 없어야 합니다.\n- 각 스티커는 균일한 흰색 테두리를 가져 스티커처럼 보여야 합니다.\n- 이미지에 불필요하거나 분리된 요소가 없어야 합니다.\n- 텍스트는 엄격히 금지하거나, 텍스트가 100% 정확하도록 보장해야 합니다(텍스트 없는 것을 선호)."
  },
  {
    id: 132,
    title: '"타이타닉" 포즈 패러디',
    category: '인물 & 캐릭터',
    author: '@balconychy',
    sourceUrl: 'https://x.com/balconychy/status/1909916265067557299',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/23/example_titanic_q_realistic.png',
    prompt: "Transform the person in the attached image into a cute chibi-style 3D character.\nScene: On the pointed bow of a luxurious cruise ship.\nThe man stands behind the woman at the bow, holding her waist with both hands. The woman is wearing a dress, arms spread wide, facing the wind, with a joyful and liberated expression on her face—just like the iconic scene from Titanic.\nThe sky is painted in warm sunset tones, and the vast ocean stretches beneath the ship.\nOnly the characters should be in chibi 3D style; the rest of the environment should be realistic.",
    prompt_ko: "첨부된 이미지 속 인물을 귀여운 꼬마 스타일의 3D 캐릭터로 변환해주세요.\n장소: 호화로운 유람선의 뾰족한 뱃머리.\n남자는 뱃머리에 있는 여자 뒤에 서서 양손으로 그녀의 허리를 잡고 있습니다. 여자는 드레스를 입고 양팔을 활짝 벌린 채 바람을 맞으며, 타이타닉의 상징적인 장면처럼 기쁘고 해방된 표정을 짓고 있습니다.\n하늘은 따뜻한 일몰 색조로 칠해져 있고, 배 아래에는 광활한 바다가 펼쳐져 있습니다.\n캐릭터만 꼬마 3D 스타일이어야 하며, 나머지 환경은 사실적이어야 합니다."
  },
  {
    id: 136,
    title: 'Q-버전 이모티콘 스티커 팩 제작',
    category: '인물 & 캐릭터',
    author: '@dotey',
    sourceUrl: 'https://x.com/dotey/status/1909800530739679488',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/27/example_chibi_emoji_pack.png',
    prompt: "Create a brand-new set of chibi-style stickers featuring the user as the main character, with six unique poses:\n  1.\tMaking a playful peace sign with both hands and winking.\n  2.\tTearful eyes and slightly trembling lips, showing a cute crying expression.\n  3.\tArms wide open in a warm, enthusiastic hug pose.\n  4.\tLying on their side asleep, resting on a tiny pillow with a sweet smile.\n  5.\tPointing forward with confidence, surrounded by shining visual effects.\n  6.\tBlowing a kiss, with heart symbols floating around.\nMaintain the chibi aesthetic:\n– Exaggerated, expressive big eyes\n– Soft facial lines\n– Playful, short black hairstyle\n– A white outfit with a bold neckline design\nBackground: Vibrant red with star or colorful confetti elements for decoration. Leave some clean white space around each sticker.\nAspect ratio: 9:16",
    prompt_ko: "사용자를 주인공으로 한 새로운 꼬마 스타일 스티커 세트를 여섯 가지 독특한 포즈로 만들어 주세요:\n  1. 양손으로 장난스럽게 브이 포즈를 하며 윙크하기.\n  2. 눈물이 그렁그렁하고 입술이 살짝 떨리는 귀여운 우는 표정.\n  3. 따뜻하고 열정적인 포옹 자세로 두 팔을 활짝 벌리기.\n  4. 작은 베개를 베고 옆으로 누워 달콤한 미소를 지으며 잠자기.\n  5. 빛나는 시각 효과에 둘러싸여 자신감 있게 앞으로 손가락질하기.\n  6. 주변에 하트 기호가 떠다니는 키스 날리기.\n꼬마 미학 유지:\n– 과장되고 표현력 있는 큰 눈\n– 부드러운 얼굴 선\n– 장난기 있는 짧은 검은색 헤어스타일\n– 대담한 네크라인 디자인의 흰색 의상\n배경: 별이나 화려한 색종이 조각으로 장식된 생생한 빨간색. 각 스티커 주위에 깨끗한 흰색 공간을 남겨두세요.\n가로세로 비율: 9:16"
  },
  {
    id: 140,
    title: '유명 회화 캐릭터 OOTD',
    category: '인물 & 캐릭터',
    author: '@ZHO_ZHO_ZHO',
    sourceUrl: 'https://x.com/ZHO_ZHO_ZHO/status/1909892294217781714',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/29/example_pearl_earring_ootd.png',
    prompt: "Generate a Q-style 3D C4D-rendered character based on the person in the photo, dressed in a fashion-forward “outfit of the day” (OOTD) inspired by a specific profession.\nProfession: Fashion Designer\n– Keep the original facial features and character pose\n– Stylize the character with a cute, long-legged chibi proportion\n– Outfit and accessories should reflect the profession, including trendy designer wear, glasses, sketchbook or tablet, and stylish shoes\n– Match the outfit with fashion accessories to complete the look\n– Use a solid background color that complements the character’s overall color palette (no gradients or textures)\n\nComposition: Aspect ratio: 9:16\nTop text: “OOTD”\nLeft side: the full-body chibi character wearing the complete outfit\nRight side: individual clothing items and accessories laid out separately, as if in a style breakdown",
    prompt_ko: "사진 속 인물을 바탕으로 특정 직업에서 영감을 받은 패셔너블한 '오늘의 의상'(OOTD)을 입은 Q-스타일 3D C4D 렌더링 캐릭터를 생성하세요.\n직업: 패션 디자이너\n– 원래의 얼굴 특징과 캐릭터 포즈 유지\n– 귀엽고 다리가 긴 꼬마 비율로 캐릭터 스타일링\n– 트렌디한 디자이너 의류, 안경, 스케치북 또는 태블릿, 스타일리시한 신발 등 직업을 반영하는 의상 및 액세서리\n– 의상과 패션 액세서리를 매치하여 룩 완성\n– 캐릭터의 전체적인 색상 팔레트를 보완하는 단색 배경색 사용 (그라데이션이나 질감 없음)\n\n구성: 가로세로 비율: 9:16\n상단 텍스트: 'OOTD'\n왼쪽: 전체 의상을 입은 전신 꼬마 캐릭터\n오른쪽: 스타일 분석처럼 개별 의류 아이템과 액세서리를 따로 배치"
  },
  {
    id: 146,
    title: '3D Q-버전 가족 웨딩 사진',
    category: '인물 & 캐릭터',
    author: '@balconychy',
    sourceUrl: 'https://x.com/balconychy/status/1909426314643222595',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/33/example_family_wedding_photo_q.png',
    prompt: "Transform the people in the photo into chibi-style 3D characters. The parents are dressed in Western wedding attire — the father in a formal suit, the mother in a wedding gown. The child is a beautiful flower girl holding a bouquet.\n\nThe background features a colorful floral arch.\nThe characters are in 3D chibi style, while the environment is photorealistic.\nThe entire scene is placed inside a photo frame.",
    prompt_ko: "사진 속 인물들을 꼬마 스타일의 3D 캐릭터로 변환해주세요. 부모님은 서양식 웨딩 복장을 하고 있습니다 — 아버지는 정장을, 어머니는 웨딩드레스를 입고 있습니다. 아이는 부케를 든 아름다운 화동입니다.\n\n배경에는 화려한 꽃 아치가 있습니다.\n캐릭터들은 3D 꼬마 스타일이며, 환경은 사실적입니다.\n전체 장면은 사진 액자 안에 배치됩니다."
  },
  {
    id: 149,
    title: '화난 소녀 사장님 일본식 2컷 만화',
    category: '인물 & 캐릭터',
    author: '@hellokaton',
    sourceUrl: 'https://x.com/hellokaton/status/1910900979194646959',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/40/example_two_panel_manga_president.png',
    prompt: `Create a two-panel vertical manga in a cute Japanese anime style, theme: “The Daily Work Life of a Girl President.”\n\nCharacter Design:\nTransform the person in the uploaded image into a cute, moe-style anime girl while preserving all key details from the photo — including the outfit (a suit), hairstyle (bright golden-yellow), and facial features.\n\nPanel 1:\n- Expression: Pouting, disappointed, resting her cheek on one hand\n- Text box: “What do I dooo?! He won’t take my call! (；´д｀)”\n- Scene: Warm-toned office, with the U.S. flag in the background. On the desk: a pile of hamburgers and a vintage red rotary phone. The character is on the left side of the frame, the phone on the right.\n\nPanel 2:\n- Expression: Furious, face red with anger, gritting teeth\n- Action: Slams the desk hard, making the hamburgers jump\n- Speech bubble: “Hmph! Double the tariffs! Ignoring me is their loss! ( \`д´ )”\n- Scene: Same office, now a complete mess\n\nAdditional Notes:\n- Use a cute, casual handwritten font for all text\n- Keep the composition full and expressive, with adequate space for dialogue and intentional white space\n- Aspect ratio: 2:3\n- The overall visual tone should be colorful and energetic, with a distinctly cartoony style`,
    prompt_ko: "귀여운 일본 애니메이션 스타일의 세로 2컷 만화를 그려주세요. 테마: '소녀 사장님의 일상 업무'.\n\n캐릭터 디자인:\n업로드된 이미지 속 인물을 귀여운 모에 스타일의 애니메이션 소녀로 변신시키되, 의상(정장), 헤어스타일(밝은 황금색), 얼굴 특징 등 사진의 모든 주요 디테일을 유지해주세요.\n\n1컷:\n- 표정: 삐치고, 실망한 채 한 손으로 뺨을 괴고 있음\n- 텍스트 상자: '어떡하지?! 전화를 안 받잖아! (；´д｀)'\n- 장면: 따뜻한 톤의 사무실, 배경에 미국 국기. 책상 위에는 햄버거 더미와 빈티지 빨간색 다이얼 전화기. 캐릭터는 프레임 왼쪽에, 전화기는 오른쪽에 위치.\n\n2컷:\n- 표정: 격분하여 얼굴이 빨개지고 이를 악물고 있음\n- 행동: 책상을 세게 내리쳐 햄버거가 튀어 오름\n- 말풍선: '흥! 관세 두 배로 올려! 날 무시한 건 그들 손해지! ( `д´ )'\n- 장면: 같은 사무실, 이제 완전히 엉망진창\n\n추가 사항:\n- 모든 텍스트에 귀엽고 캐주얼한 손글씨 폰트 사용\n- 대화와 의도적인 여백을 위한 충분한 공간을 확보하여 구성을 꽉 차고 표현력 있게 유지\n- 가로세로 비율: 2:3\n- 전체적인 시각적 톤은 다채롭고 활기차며, 뚜렷하게 만화적인 스타일"
  },
  {
    id: 151,
    title: '3D Q-버전 커플 스노우 글로브',
    category: '인물 & 캐릭터',
    author: '@balconychy',
    sourceUrl: 'https://x.com/balconychy/status/1909908568129655248',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/42/example_3d_q_snowglobe_couple.png',
    prompt: "Transform the person in the attached image into a snow globe scene.\nOverall environment: The snow globe is placed on a tabletop by the window, with a blurred, warm-toned background. Sunlight passes through the globe, casting golden sparkles that gently illuminate the surrounding darkness.\nInside the globe: The characters are in a cute chibi-style 3D design, gazing at each other with eyes full of love.",
    prompt_ko: "첨부된 이미지 속 인물을 스노우 글로브 장면으로 변환해주세요.\n전체 환경: 스노우 글로브는 창가 탁자 위에 놓여 있고, 배경은 흐릿하고 따뜻한 톤입니다. 햇빛이 글로브를 통과하며 금빛 반짝임을 만들어 주변의 어둠을 부드럽게 비춥니다.\n글로브 내부: 캐릭터들은 귀여운 꼬마 스타일의 3D 디자인으로, 사랑이 가득한 눈으로 서로를 바라보고 있습니다."
  },
  {
    id: 152,
    title: '귀여운 꼬마 마트료시카 인형 (진주 귀걸이를 한 소녀)',
    category: '인물 & 캐릭터',
    author: '@ZHO_ZHO_ZHO',
    sourceUrl: 'https://x.com/ZHO_ZHO_ZHO/status/1911669883315818497',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/43/example_matryoshka_pearl_earring.png',
    prompt: "Transform the person in the image into a set of cute chibi-style Russian nesting dolls (🪆), with a total of five dolls arranged from largest to smallest. Place them on an elegant wooden table. Horizontal aspect ratio: 3:2.",
    prompt_ko: "이미지 속 인물을 귀여운 꼬마 스타일의 러시아 전통 인형(마트료시카 🪆) 세트로 변환해주세요. 총 다섯 개의 인형을 가장 큰 것부터 가장 작은 것 순서로 배열하고, 우아한 나무 테이블 위에 놓아주세요. 가로세로 비율: 3:2."
  },
  {
    id: 153,
    title: 'RPG 스타일 캐릭터 카드 제작',
    category: '인물 & 캐릭터',
    author: '@berryxia_ai',
    sourceUrl: 'https://x.com/hc_dsn/status/1912367201476309396',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/44/example_rpg_card_designer.png',
    prompt: "Create a digital character card in RPG collectible style.\nThe subject is a {Programmer}, standing confidently with tools or symbols relevant to their job.\nRender it in 3D cartoon style, soft lighting, vivid personality.\nInclude skill bars or stats like [Skill1 +x], [Skill2 +x, e.g., Creativity +10, UI/UX +8].\nAdd a title banner on top and a nameplate on the bottom.\nFrame the card with clean edges like a real figure box.\nMake the background fit the profession's theme.\nColors: warm highlights, profession-matching hues.",
    prompt_ko: "RPG 수집형 스타일의 디지털 캐릭터 카드를 만들어 주세요.\n주제는 {프로그래머}이며, 자신의 직업과 관련된 도구나 상징물을 들고 자신감 있게 서 있습니다.\n3D 만화 스타일, 부드러운 조명, 생생한 개성으로 렌더링해주세요.\n[스킬1 +x], [스킬2 +x, 예: 창의력 +10, UI/UX +8]과 같은 스킬 바나 능력치를 포함해주세요.\n상단에는 제목 배너를, 하단에는 이름표를 추가해주세요.\n실제 피규어 상자처럼 깔끔한 테두리로 카드를 프레임 처리해주세요.\n배경은 직업의 테마에 맞게 만들어주세요.\n색상: 따뜻한 하이라이트, 직업에 맞는 색조."
  },
  {
    id: 154,
    title: '3D 꼬마 스타일 대학 의인화 마스코트',
    category: '인물 & 캐릭터',
    author: '@dotey',
    sourceUrl: 'https://x.com/dotey/status/1911988003729203648',
    inputImages: [],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/45/example_university_mascot_npu.png',
    prompt: "Create a personified 3D chibi-style anime girl character representing {Northwestern Polytechnical University}, embodying the school’s distinctive strengths in {aeronautics, astronautics, and marine engineering}.",
    prompt_ko: "{서북공업대학}을 대표하는 의인화된 3D 꼬마 스타일 애니메이션 소녀 캐릭터를 만들어 주세요. 이 캐릭터는 학교의 독특한 강점인 {항공, 우주, 해양 공학}을 구현해야 합니다."
  },
  {
    id: 191,
    title: '사이버펑크 캐릭터',
    category: '인물 & 캐릭터',
    author: 'Gemini',
    sourceUrl: '#',
    inputImages: ['https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/person/input_1.jpg'],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/person/output_1.jpg',
    prompt: 'Turn this person into a cyberpunk character with neon tattoos and robotic implants.',
    prompt_ko: '이 사람을 네온 문신과 로봇 임플란트가 있는 사이버펑크 캐릭터로 바꿔줘.',
  },
  {
    id: 192,
    title: '픽사 스타일 캐릭터',
    category: '인물 & 캐릭터',
    author: 'Gemini',
    sourceUrl: '#',
    inputImages: ['https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/person/input_2.jpg'],
    outputImage: 'https://raw.githubusercontent.com/jamez-bondos/awesome-gpt4o-images/main/cases/person/output_2.jpg',
    prompt: 'Redraw this person in the style of a Pixar character.',
    prompt_ko: '이 사람을 픽사 캐릭터 스타일로 다시 그려줘.',
  }
];
